dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: VMDNCSiVCOUc2kTFTOY0Bw71Q+We/E/dEcwc2W4wi64kpFXNmMopUTX6Ai+iFXU40bwLIUWSerjqx92329gN0re6tKn0ucuJKbv9mh70mk2am8pXAkzRscFSfFzeaikG5BqGJAbYx5ARCPEa4Ln+9kgolzGjq5EMzXsGy99j3FzCdmt6zJOEBjLEtJDpOL+Yvb9iZmim3XJFyUuSI+Rtxr7RvgDlpdw5mxI7dCrslyANN+B2RvRHMsiPvhqlxCVNFfPHWoY8l/t7KbVcVQQrjrGv7TIBxql1ctXxCVC38oOUkCp+H1CxTefdpzPHuJ7KhTKGKnKyIaytH4Qe/UYc45WbbyHd38blQz1sFvagsrjBaLaEtRN4jpXF0l19VEouWeQfNDRGgVyqXXtmmLUfr12em4vYZgJfEDdVS2HH3+MFojVFTfb1D+fjiHxqkjalDoi14rUpgpaLuwsEWmJwnGKrKkFLPtdOzsjCiL4V7Lkh1rSfIMfvW9ix0iUFtTa453xH9t+/BKlNjLl6gaxzHl0jh2g1U/1ezQE8HAyZbg9NS0OQ/FhyjwTihgodIJNRgn6Ye2Mj9lf0XIFJUWjjBKZQ8kigTakzFPF9dis5Quf/9WQDGJn4OGoQC3KnYhTPsYZhFiqp5/IRfWaUpSxUgs6MPuNKLC2iBdZBoaNYVT4=
  - secure: c+b7OQvcj4dncOQ2eoPqUQTI/WwYCZEgcbzj2cHh8Q9Pn8PTBabNRLxqmf6SSyWNeNt7p1lLduEchIv6b+xfMMQ6eWK9KfbUVBq8XyOvG9MNUtr9oq/2DYYd1AmCfayvA4ZS1enuRpsbh8xOE+5pv+4b5ByBEXHLzuBTWCbWJxpW8iQf7RsjHBWTnF0Ptwrblt2pJGnpC/IaZZW7i/QxRmzJfh7v9fZV8zJZGZeJ0ojJ9ktTg9CS77kbjEHFxzRj6WmI3e4ZhNEqRTkjtaaK5j8IYlJre33qxhE4ugoh2tNRAHN8iy1B2doq3nehN30hG2en+DiKSv50IhcE+M5MAkJZMEIhT9ppGR7qylf7SkpxL9M50SMrizR5vzu3PDXGttwIy8bZm2Wkevea21YrVagIs6CFXu4ZxAKh81Xtd7xnSEu4dTb517BlpviSXFEKwN8yKkJSrz9Krl6AlP36DXKIslmZfHN84ZzMeVWQmQX427G9Ugay+flOgjcK/3k6JncQUhvJ+9J4dYgBiImYFNaQ6ty8YgIcHwgfvq2zwDTRD+wuTHWvFLK5YbxTcduhAjV2BFa4AaypnBKz3PJrobndAOwY3EpAtTDhcP7xv69schz1+LsY3qGrsntg+Zf6p8yNTQiC+CXtB6N7KZfqU9gvmxp8lyuGfFeKQjtuzVM=
  - secure: cnTbAS6KcxyyiBkuuGV1VJ1ZyF2bu5xbtVBIJYe+0XwyePbSqorVYn1wCnBcs/iMxWnIoFUlPvS3TystpQ5Bq778XvcQOo4/nrnuovn9P9mSSjCg62hg1/63yNVMQNqp6YLJOz0ygPGlhwiMthiMgWNQqtogBIV9hnKoLCjF9FhkuQSdmVJLJnvnabNNhk9rYo/3nO+OC3ST0de143ret0lL5QflvaRUJZJKaRwAAY3J/K2+C8UrBdFuTYEF7VGcXM+UqpdecJQXozJDTSAoUSJLzc097Sj27CN6ap4QBKH67ZUkRaNJpnz4jK1EVqowJzmTB9JkU4tOsFPDV14l+1+/Xy9/YQEMRGfCmZJ3cMpLInt0j5pf8K7s/D+ldvCSrH3tynjbL4ycaLraJWSq8phUrxN5JwicuBJpqdp5IKYP9f+VL3ra5eICHV4LFBfiFEn1dlLSyUOHt27Szb6aIgnVGBwsrHug40+5MLcNc1yLeADpUopRTPU6YMsdFc2SbqMqbw8BBc3Au0R15yPNmLKfxaoDS8fp2YKANEX6VEiemf0Ik/IXOy1zj6LUp8uD47VvXECkiQxDT6fDyHt/BK6jUKuUyZdrA+8roxf3uJJRaAJxX790JDLzLRemWz7XkYnmPWUBNcWGPIWECnKSTTWlk7I2zfFsBMG9wfOerkE=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
